exclude: '^docs/conf.py'

repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
      exclude: \.md
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: check-xml
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: mixed-line-ending
      args: ["--fix=no"]
    - id: flake8
      args: ["--max-line-length=79"]
      exclude: ^notebooks

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.6
    hooks:
    - id: reorder-python-imports
      application-directories: .:src
      exclude: ^notebooks

-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      exclude: ^notebooks

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    - id: flake8
      args: ["--max-line-length=79"]
      exclude: ^notebooks

-   repo: local
    hooks:
    - id: format-ipynb
      name: format-ipynb
      entry: jupytext --from ipynb --pipe black --check flake8 --pre-commit
      pass_filenames: false
      language: python
    - id: jupytext
      name: jupytext
      entry: jupytext --from ipynb --to py:light --pre-commit
      pass_filenames: false
      language: python

-   repo: https://github.com/MartinThoma/check-pip-compile
    rev: 0.1.0
    hooks:
    - id: check-pip-compile
      args: ["requirements.in"]  # it's recommended to specify the files you want

-   repo: https://github.com/myint/eradicate
    rev: v2.0.0
    hooks:
    - id: eradicate
      exclude: ^notebooks

-   repo: https://github.com/yunojuno/pre-commit-xenon
    rev: c7e19e94a58937da5d0fc99cb00917d2e0688d99
    hooks:
    - id: xenon
      args: ["--max-average=A", "--max-modules=C", "--max-absolute=C"]
      exclude: ^notebooks

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
    - id: mypy
      additional_dependencies: [attrs~=19.3]
      exclude: ^(notebooks|tests)/

-   repo: https://github.com/kplaube/pre-commit-dodgy
    rev: master # Use `master` for the latest version
    hooks:
    - id: dodgy

-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2 # Update me!
    hooks:
    - id: bandit

-   repo: https://github.com/asottile/dead
    rev: v1.3.0
    hooks:
    - id: dead
      args: [
          "--files '(^|/)(src|scripts)/'",
      ]
